### ISSUE TITLE
Missing prerequisites

### ISSUE THREAD

**Issue by asarkar** [sebgoa/oreilly-kubernetes#1]
1. Flash
2. Subscription to Slack channel

For 1, if you can avoid it, please don't use Flash. My default Chrome browser didn't work, neither did Safari until I enabled Flash for the training. This is 2017, who uses Flash anymore? And none of the flash based controls in the demo were actually used (Q&A etc).

For 2, if you send an email ahead of time with an invitation to the Slack channel, people can subscribe.

**Comment by sebgoa** [comment]
I am going to punt on that one, I don't manage the logistics. I will let Lindsay know.

**Comment by sebgoa** [comment]
For SLACK, O'Reilly should have sent you the slack invite, it should be in your inbox.
but i will let them know to make sure they send it to all.
